# Generated by Django 2.0.4 on 2018-04-30 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('scan', models.FileField(upload_to='')),
                ('transcription', models.FileField(upload_to='')),
            ],
        ),
    ]
